### ISSUE TITLE
使用docker的--net=host部署时使用，获取网卡存在问题，无法获取正确网卡

### ISSUE THREAD

**Issue by zengruitester** [asura-pro/pea#2]
![image](https://user-images.githubusercontent.com/33141728/67648057-7e782580-f96f-11e9-8b44-bc762d139cc1.png)

**Comment by xcorpio** [comment]
这种情况可以在配置中 指定IP, https://github.com/asura-pro/pea/blob/master/conf/application.conf#L8

也可以输出个 环境变量: `export ADDRESS=172.17.0.1`

**Comment by zengruitester** [comment]
我在部署中取消了--net=host模式  使用了 --env ADDRESS=宿主机ip解决了此问题

**Comment by zengruitester** [comment]
问题以解决
