### ISSUE TITLE
只想使用dubbo功能，可以直接增加jar包依赖么

### ISSUE THREAD

**Issue by TestRong** [asura-pro/pea#3]

**Comment by xcorpio** [comment]
直接添加 jar 包还不行，下个版本我支持下吧。
直接吧Dubbo 的 Interface 写在 git 库中是可以的，像这样 https://github.com/asura-pro/pea-simulations/blob/master/src/main/java/pea/dubbo/api/GreetingService.java

**Comment by xcorpio** [comment]
https://github.com/asura-pro/pea/releases/tag/v0.7.0

这个版本可以上传 jar包

**Comment by TestRong** [comment]
> https://github.com/asura-pro/pea/releases/tag/v0.7.0
> 
> 这个版本可以上传 jar包

可以给个联系方式么。。
